### ISSUE TITLE
never loaded

### ISSUE THREAD

**Issue by ljci** [lockys/AwesomeSearchReact#3]
![Screenshot 2024-03-24 at 7 04 11 PM](https://github.com/lockys/AwesomeSearch2021/assets/44239616/494a5bab-ab18-4b0d-a1d7-f483c441e303)

The page is always showing like above and never loaded

**Comment by tiagorangel2011** [comment]
+1, it seems it's fetching for "undefined/undefined" instead of the actual awesome repo url

**Comment by lockys** [comment]
@ljcliu 
Server was crashed months ago. I fixed it in the latest commit. Thanks for reporting this as I do not actively maintain this project ady but I will try to keep this site up for those still using this site.
